### PR TITLE
103 Update

### PR DESCRIPTION
**Pull request by matzew**
@fjuma mind to review ?

### CODE REVIEW

**Comment by fjuma** [comment]
Looks good to me.

**Comment by fjuma** [comment]
It might be good to lock the migration files (i.e., add entries in https://github.com/aerogear/openshift-origin-cartridge-aerogear-push-wildfly/blob/master/metadata/managed_files.yml) to make sure they can't accidentally get deleted.

**Comment by matzew** [comment]
@fjuma done

**Comment by fjuma** [comment]
Great.

Just found that the aerogear-push/usr/lib/migrator directory can be used to store the migration files after all as long as the installation is moved to bin/setup:

https://github.com/matzew/openshift-origin-cartridge-aerogear-push-wildfly/pull/1

**Comment by matzew** [comment]
cool, merged

**Comment by sebastienblanc** [comment]
I have tested the cartridge with success : 

- App creation / variants creation
- sending push notifications :
  * helloworld iOS
  * helloworld Android
- Dashboard numbers are correct 
- Account Management OK 

:+1:

**Pull request merged**
