### PR TITLE
Updating to latest 1.1.3.Final of UPS

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
@viezel Hi, mind giving this a try ?

**Comment by viezel** [comment]
How? 
You have not created the cartridge update yet, right? 
I dont see any way to update from the openshift console.

**Comment by matzew** [comment]
@viezel right, will get to that :)

**Comment by nuno** [comment]
@matzew, I installed and I do not see nothing related to titanium, is normal?

**Pull request merged**
