### PR TITLE
J groups removal

### PR DESCRIPTION
**Pull request by matzew**
@fjuma mind to test and review ?

### CODE REVIEW

**Comment by fjuma** [comment]
@matzew These changes look good to me. I also verified that I'm able to successfully create a new app as well.

**Comment by matzew** [comment]
@sebastienblanc @kpiwko can you take a look too ?

**Comment by kpiwko** [comment]
@smiklosovic can you have a look on Monday?

**Comment by kpiwko** [comment]
@matzew the changes looks good to me but it would need some testing

**Comment by matzew** [comment]
@smiklosovic @kpiwko any comment ?

**Comment by smiklosovic** [comment]
i was pto yesterday, ill give it a shot

**Comment by smiklosovic** [comment]
:+1:

**Pull request merged**
