### PR TITLE
Updating WAR and metainfo for new version

### PR DESCRIPTION
**Pull request by matzew**
TESTING via:

```
rhc create-app --gear-size medium --no-git ups112 "https://cartreflect-claytondev.rhcloud.com/reflect?github=aerogear/openshift-origin-cartridge-aerogear-push&commit=4801dafa0d8be7e80e51a74ddb15336ad3d6b83f"
```

### CODE REVIEW

**Comment by matzew** [comment]
@viezel mind giving this a try ? 

I have update the WAR files and the metadata. The WAR files I did create by checking out the tag:
* https://github.com/aerogear/aerogear-unifiedpush-server/tree/1.1.2.Final

and running `mvn clean install -Popenshift,test`, as discussed [here](https://github.com/aerogear/aerogear-unifiedpush-server/tree/1.1.2.Final#openshift)

**Comment by viezel** [comment]
but I have a running version, how do I upgrade/migrate it? I dont want to create a new instance

**Comment by matzew** [comment]
@fjuma what's the easiest way to update? I think we don't have git repos, of the WAR files .

Would SSH into the instance help, and just copy the files in tehre ?

**Comment by fjuma** [comment]
@matzew I don't think copying the files into the deployments directory will work because I think that directory is locked. One way to quickly test an update without creating a new instance might be to SSH into the instance and use the CLI to deploy the new WAR files. The CLI can be accessed like this:

```$OPENSHIFT_AEROGEAR_PUSH_DIR/bin/tools/jboss-cli.sh -c --controller=$OPENSHIFT_AEROGEAR_PUSH_IP:$OPENSHIFT_AEROGEAR_PUSH_MANAGEMENT_HTTP_PORT```

**Comment by matzew** [comment]
> because I think that directory is locked

ah, you are right! I now recall that!

@viezel I will test the CLI from @fjuma and will keep ya posted, ok ?

**Comment by viezel** [comment]
@matzew that would be very nice.
Note: I was looking into the `rhc` CLI, but not sure if it applies here.
https://developers.openshift.com/managing-your-applications/client-tools.html

**Comment by matzew** [comment]
@viezel nope, it's the jboss CLI.

On it

**Comment by matzew** [comment]
@viezel Ok, it worked for me!

⚠️  it might not work for you 😁 

Here are my steps:
1) `rhc ssh YOUR_NAME`
2) `cd aerogear-push`
3) Download the new WAR files:
* `wget https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/raw/1.1.2.Final/versions/1.1.2/standalone/deployments/auth-server.war`
* `wget https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/raw/1.1.2.Final/versions/1.1.2/standalone/deployments/ag-push.war`

4) Start the deployer, on the shell:
`$OPENSHIFT_AEROGEAR_PUSH_DIR/bin/tools/jboss-cli.sh -c --controller=$OPENSHIFT_AEROGEAR_PUSH_IP:$OPENSHIFT_AEROGEAR_PUSH_MANAGEMENT_HTTP_PORT`
5) perform the actual deploy:
* `deploy --force ./auth-server.war`
* `deploy --force ./ag-push.war`

Redeploy should occur! (You can check via `rhc tail YOUR_NAME`)

Verification, noticed on the UI that [AGPUSH-1498](https://issues.jboss.org/browse/AGPUSH-1498) is fixed (or the enhanced logging, [https://issues.jboss.org/browse/AGPUSH-1592](AGPUSH-1592) (can see it via the tail))

**Comment by viezel** [comment]
@matzew that worked on the first server, but I got outofmemory on the second. So the server crashed. 
How do I roll back a deploy ?

Is there any good tutorial/guide site for jboss CLI deployment?

**Comment by matzew** [comment]
@viezel oh, I am sorry to hear this! 

The OutOFMemory - is that based on a small gear ? What's the version you had there before?

**Comment by viezel** [comment]
I had 1.1.0. Yes the crashing instance is a small instance, so thats maybe why. 
But in order for me to feel comfatable using your software in production with alot of clients, i need to know how I can deploy (at best atomic symlink), rollback etc.. 
Isnt there any knowledge base on this?

I cannot be the first that wats this from openshift and jboss  :)

**Comment by matzew** [comment]
@viezel yeah, I see your point. :-)

Since this is a community cartridge, we never added much support for updates, but sure, we can make that work.

Are you able to join IRC, so that we can do a bit more 'real time' conversation, where we can try a few things, to recover your broken gear?

BTW. since 1.1.0 version (and pre releases) we require medium. I am surprised it ever worked

**Comment by matzew** [comment]
Are you able to upgrade that box? to medium ?

**Pull request merged**
