### PR TITLE
1.1.0.final

### PR DESCRIPTION
**Pull request by matzew**
yet another try for 1.1.0.Final

### CODE REVIEW

**Comment by lfryc** [comment]
rhc create-app --gear-size medium --no-git YOUR_APP_NAME "https://cartreflect-claytondev.rhcloud.com/reflect?github=aerogear/openshift-origin-cartridge-aerogear-push&commit=4d9cdf58de32d0958a9f0ada3d6468e194d8e1b6"

**Comment by matzew** [comment]
@lfryc wanna merge ?

**Comment by lfryc** [comment]
Not yet please

**Comment by lfryc** [comment]
Tested successfully with `unifiedpush-push-helloworld/cordova` sample on `android`, `ios` and `wp8`.

Found one small issue in UI: https://issues.jboss.org/browse/AGPUSH-1524

**Comment by lfryc** [comment]
Merging...

**Comment by lfryc** [comment]
Landed now: https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/commit/3bf2ed4c5d6bbf885d934c2533ef122924e0fcd0 :rocket:

**Pull request merged**
